name: Python Calculator App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov pytest-pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with pylint
      run: |
        # Create an empty .env file for testing
        touch .env
        echo "APP_ENV=testing" > .env
        echo "LOG_LEVEL=ERROR" >> .env
        echo "DEMO_API_KEY=test_key" >> .env
        echo "ENABLE_ADVANCED_OPERATIONS=true" >> .env
        
        # Create logs directory
        mkdir -p logs
        
        # Run pylint
        python -m pytest --pylint || true  # Continue even if linting fails
    
    - name: Test with pytest and coverage
      run: |
        # Run tests with coverage
        python -m pytest --cov
    
    - name: Generate coverage report
      run: |
        python -m pytest --cov --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
